# Generated by Django 3.0.4 on 2020-03-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20200316_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesmodel',
            old_name='file_to_upload',
            new_name='uploaded_file',
        ),
    ]
